hbyngj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from hbyngj import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index_view, name='index'),
    url(r'^product/', include('product.urls', namespace="product")),
]

product/urls.py
from django.conf.urls import url, include
from product import views

urlpatterns = [
    url(r'^$', views.product, name='product_index'),
    url(r'^(?P<category_id>[0-9]+)$', views.product, name='product'),
    url(r'^detail/(?P<product_id>[0-9]+)$', views.product_detail, name='product_detail')
]

banner/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Banner(models.Model):
    title = models.CharField(max_length=256)
    image = models.ImageField(upload_to='banner')
    visible = models.BooleanField(default=True, null=False, blank=False)
    weight = models.IntegerField(default=0)

news/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=256, null=False, blank=False)
    visible = models.BooleanField(default=True, null=False, blank=False)
    weight = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name


class News(models.Model):
    title = models.CharField(max_length=256, null=False, blank=False)
    content = models.TextField()
    created_time = models.DateTimeField()
    visible = models.BooleanField(default=True, null=False, blank=False)

product/models.py
from __future__ import unicode_literals

from datetime import datetime
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=256, null=False, blank=False)
    visible = models.BooleanField(default=True, null=False, blank=False)
    weight = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=256, null=False, blank=False)
    image = models.ImageField(upload_to='product')
    visible = models.BooleanField(default=True, null=False, blank=False)
    created_time = models.DateTimeField(null=False, default=datetime.now())
    category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.title

banner/controller.py
from banner.models import Banner


class BannerController(object):
    @classmethod
    def get_banners(cls):
        return Banner.objects.filter(visible=True).order_by("-weight")

banner/views.py
from django.shortcuts import render

# Create your views here.

hbyngj/views.py
from django.shortcuts import render

# Create your views here.
from django.template.response import TemplateResponse
from django.views.decorators.http import require_GET
from product.controller import CategoryController, ProductController


@require_GET
def index_view(request, template_name='index.html'):

    categories = CategoryController.get_categories()

    products = ProductController.get_product_index(categories[0])

    return TemplateResponse(request,
                            template=template_name,
                            context={
                                "categories": categories,
                                "products": products,
                            })

news/views.py
from django.shortcuts import render

# Create your views here.
from django.template.response import TemplateResponse
from django.views.decorators.http import require_GET


@require_GET
def index_view(request, template_name='index.html'):
    agent = request.META.get('HTTP_USER_AGENT', None)

    return TemplateResponse(request,
                            template=template_name,
                            context={

                            })

product/controller.py
from product.models import Category, Product


class CategoryController(object):
    @classmethod
    def get_category(cls, category_id):
        return Category.objects.get(pk=category_id)

    @classmethod
    def get_categories(cls):
        return Category.objects.filter(visible=True).order_by("-weight")


class ProductController(object):
    @classmethod
    def get_product(cls, product_id):
        return Product.objects.get(pk=product_id)

    @classmethod
    def get_product_index(cls, category):
        return Product.objects.filter(category=category, visible=True)[0:12]

    @classmethod
    def get_product_by_category(cls, category):
        return Product.objects.filter(category_id=category, visible=True)

product/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from django.template.response import TemplateResponse
from product.controller import ProductController, CategoryController


def product(request, category_id='', template_name='product.html'):

    if not category_id:
        categories = CategoryController.get_categories()
        category = categories[0]
        category_id = category.id
    else:
        category = CategoryController.get_category(category_id)

    products = ProductController.get_product_by_category(category_id)
    return TemplateResponse(request,
                                template=template_name,
                                context={
                                    "products": products,
                                    "category": category,
                                })


def product_detail(request, product_id, template_name='product_detail.html'):
    try:
        product = ProductController.get_product(product_id)
    except ObjectDoesNotExist:
        raise Http404

    related_products = ProductController.get_product_by_category(product.category_id)
    related_products = related_products.filter(~Q(pk=product.id))

    return TemplateResponse(request,
                            template=template_name,
                            context={
                                "product": product,
                                "related_products": related_products,
                            })

templates/base/banner.html
<div class="banner">
    <div class="slider">
        <ul class="slider__wrapper">
            {% for item in banners %}
            <li class="slider__item">
                <a target="_blank" title="1" href="" style="background-image:url(/s/upload/{{ item.image }})">
                    <img src="/s/images/banner-2.png" alt="{{ itme.title }}" />
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

<script type="text/javascript">
    var glide = $('.slider').glide();
</script>

templates/base/base.html
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="applicable-device" content="pc,mobile" />
    <title>河北益能管件有限公司</title>



    <link href="/s/css/bootstrap.css" rel="stylesheet" />
    <link href="/s/css/glide.css" rel="stylesheet" />
    <link href="/s/css/style.css" rel="stylesheet" />
    <link href="/s/css/online.css"rel="stylesheet" />
    <script src="/s/js/jquery.min.js" type="text/javascript"></script>
    <script src="/s/js/bootstrap.js" type="text/javascript"></script>
    <script src="/s/js/jquery.glide.js" type="text/javascript"></script>
    <!--[if lt IE 9]>
    <script src="/s/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/s/js/respond.min.js" type="text/javascript"></script>
    <![endif]-->
</head>

<body>
{% block base_top %}
{% include 'base/header.html'%}
{% include 'module/contact.html'%}
{% endblock %}
{% block base_content %}{% endblock %}
{% block base_end %}
{% include 'base/footer.html'%}
{% endblock %}
</body>
</html>

templates/base/footer.html
<footer>

    <div class="copyright">
        <p>
            <a href="about.html">公司简介</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <a href="article.html">新闻中心</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <a href="product.html">产品中心</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <a href="contact.html">联系我们</a>
        </p>
        <p class="copyright_p">© 2000-2017 MojoCube All Rights Reserved. 信息产业部备案号：粤ICP备12345678号</p>
    </div>

</footer>

<script type="text/javascript" src="/s/js/common.js"></script>

<!--客服面板-->
<!--电脑版-->
<div id="cmsFloatPanel">

    <div class="ctrolPanel">
        <a class="service" href="#"></a>
        <a class="message" href="#"></a>
        <a class="qrcode" href="#"></a>
        <a class="arrow" title="返回顶部" href="#"></a>
    </div>

    <div class="servicePanel">
        <div class="servicePanel-inner">
            <div class="serviceMsgPanel">
                <div class="serviceMsgPanel-hd"><a href="#"><span>关闭</span></a></div>
                <div class="serviceMsgPanel-bd">
                    <!--在线QQ-->
                    <div class="msggroup">
                        <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=396288955&site=qq&menu=yes"><img class="qqimg" src="http://wpa.qq.com/pa?p=2:593036114:52" alt="QQ在线客服" />技术支持</a>
                    </div>
                    <!--在线MSN-->
                    <div class="msggroup">
                        <a href="" target="blank"><img class="qqimg" src="/s/images/msn.jpg" alt="MSN在线客服" /> 官方</a>
                    </div>
                    <!--在线SKYPE-->
                    <div class="msggroup">
                        <a href=""><img class="qqimg" src="/s/images/skype.gif" alt="SKYPE在线客服" /> 官方</a>
                    </div>
                    <!--淘宝旺旺-->
                    <div class="msggroup">

                    </div>
                </div>
                <div class="serviceMsgPanel-ft"></div>
            </div>
            <div class="arrowPanel">
                <div class="arrow02"></div>
            </div>
        </div>
    </div>

    <div class="messagePanel">
        <div class="messagePanel-inner">
            <div class="formPanel">

                <div class="formPanel-bd">
                    <!-- JiaThis Button BEGIN -->
                    <div class="jiathis_style_32x32">
                        <a class="jiathis_button_qzone"></a>
                        <a class="jiathis_button_tsina"></a>
                        <a class="jiathis_button_tqq"></a>
                        <a class="jiathis_button_weixin"></a>
                        <a class="jiathis_button_renren"></a>
                        <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                    </div>
                    <script type="text/javascript" src="http://v3.jiathis.com/code_mini/jia.js" charset="utf-8"></script>
                    <!-- JiaThis Button END -->
                    <a type="button" class="btn btn-default btn-xs" href="#" style="margin: 6px 0px 0px 10px;">关闭</a>
                </div>

            </div>
            <div class="arrowPanel">
                <div class="arrow01"></div>
                <div class="arrow02"></div>
            </div>
        </div>
    </div>

    <div class="qrcodePanel">
        <div class="qrcodePanel-inner">
            <div class="codePanel">
                <div class="codePanel-hd"><span style="float:left">用手机扫描二维码</span><a href="#"><span>关闭</span></a></div>
                <div class="codePanel-bd">
                    <img src="/s/images/qrcode.jpg" alt="二维码" />
                </div>
            </div>
            <div class="arrowPanel">
                <div class="arrow01"></div>
                <div class="arrow02"></div>
            </div>
        </div>
    </div>

</div>

<div id="serviceBox" style="display:none">
    <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=396288955&site=qq&menu=yes"><img class="qqimg" src="http://wpa.qq.com/pa?p=2:593036114:52" alt="QQ在线客服" />技术支持</a>
</div>

<script type="text/javascript" src="/s/js/online.js"></script>

<!--电脑版 end-->

<!--手机版-->
<nav class="navbar-default navbar-fixed-bottom footer_nav" style="background:#fafafa;">
    <div class="foot_nav"><a href="javascript:mShare()"><span class="glyphicon glyphicon-share btn-lg" aria-hidden="true"></span>分享</a></div>
    <div class="foot_nav"><a href=""><span class="glyphicon glyphicon-phone btn-lg" aria-hidden="true"></span>电话</a></div>
    <div class="foot_nav" id="serviceBtn"><a onClick="showService()"><span class="glyphicon glyphicon glyphicon-headphones btn-lg" aria-hidden="true"></span>客服</a></div>
    <div class="foot_nav"><a id="gototop" href="#"><span class="glyphicon glyphicon-circle-arrow-up btn-lg" aria-hidden="true"></span>顶部</a></div>
    <div id="mShareBox" style="position: fixed; display: none; z-index: 999; bottom: 47px; width: 100%; height: 45px; background: #fff; border-top: 1px solid #ccc; border-bottom: 1px solid #ccc; padding: 5px;">
        <!-- JiaThis Button BEGIN -->
        <div class="jiathis_style_m"></div>
        <script type="text/javascript" src="http://v3.jiathis.com/code/jiathis_m.js" charset="utf-8"></script>
        <!-- JiaThis Button END -->
    </div>
</nav>
<!--手机版 end-->

<script type="text/javascript">
    function mShare() {
        $("#mShareBox").toggle();
        $("#serviceBox").hide();
    }

    if ($(".banner .slider__wrapper li").length == 0) {
        $(".banner").addClass("emptyBanner");
    }

    function showService() {
        $("#mShareBox").hide();
        $("#serviceBox").toggle();
    }
</script>

templates/base/header.html
<header>
    <div class="topBox">
{#        <div class="borderBottom">#}
{#            <div class="container">#}
{#                <div class="welcomeBox">欢迎光临官方企业网站</div>#}
{#                <div class="languageBox">#}
{#                    <a href="#" class="en">English</a><a href="#" class="zh">中文版</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-8 logo"><a href="/"><img src="/s/images/logo.gif" alt="河北益能管件有限公司" /></a></div>

                <div class="col-xs-6 col-sm-3 col-md-2">
                    <div class="address"></div>
                </div>

                <div class="col-xs-6 col-sm-3 col-md-2">
                    <div class="tel">
                        <img src="/s/images/tel.gif" alt="" /><br />18301668322
                    </div>
                </div>

            </div>
        </div>
    </div>

    <nav class="navbar navbar-static-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
{#                <a class="navbar-brand" href="index.html"></a>#}
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">

                    <li class="dropdown" style="border-left:1px solid #ddd"><a href="/">网站首页</a></li>
                    <li class="dropdown">
                        <a href="{% url 'product:product_index' %}" class="dropdown-toggle" data-toggle="dropdown">产品中心</a><a href="#" id="app_menudown" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-menu-down btn-xs"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            {% for item in categories %}
                            <li><a class='' href='{% url 'product:product' category_id=item.id %}'>{{ item.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="pr" class="dropdown-toggle" data-toggle="dropdown">新闻中心</a><a href="#" id="app_menudown" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-menu-down btn-xs"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a class='' href='article.html'>公司新闻</a></li>
                            <li><a class='' href='article.html'>行业新闻</a></li>
                        </ul>
                    </li>

                    <li><a href="album.html">案例中心</a></li>

                    <li><a href="comment.html">在线留言</a></li>

                    <li><a href="contact.html">联系我们</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Banner -->
{% include 'base/banner.html'%}

templates/index.html
{% extends 'base/base.html'%}
{% block base_content %}
<section>

<!-- 产品 -->
<div style="padding-top: 0px; margin-top:0px; padding-bottom:10px">

    <div class="container">
        <div class="row">
        <!-- 产品中心 -->
        <div class="col-xs-12 col-sm-8 col-md-9" id="rightBox">

            <div class="newsBox" style="margin: 0;">
                <div class="titleBar">
                    <h1>产品中心</h1>
                    <span></span> <a class="rightMore" href="{% url 'product:product_index' %}">更多</a>
                </div>
            </div>

            <div class="col-sm-12 col-md-12 pad">

                <div class="productList">
                    {% for item in products %}
                    <div class="col-xs-6 col-sm-4 col-md-3 col-mm-6 productImg">
                        <a title="{{ item.title }}" href='{% url "product:product_detail" product_id=item.id %}'>
                            <span class="imgLink-hover"><span class="hover-link"></span></span>
                            <img src="/s/upload/{{ item.image }}" alt="{{ item.title }}" />
                        </a>
                        <a class="productTitle" href="{% url "product:product_detail" product_id=item.id %}" title="{{ item.title }}">
                            {{ item.title }}
                        </a>
                    </div>
                    {% endfor %}

                </div>

            </div>

        </div>

        <!-- 产品分类 -->
        <div class="col-xs-12 col-sm-4 col-md-3">

            <div class="navigationBox" id="classification">
                <div class="titleBar">
                    <h1>产品分类</h1>
                    <span></span>
                </div>
                <div class="list">
                    <ul id="firstpane">
                        {% for item in categories %}
                        <li><a class='' href='{% url 'product:product' category_id=item.id %}'>{{ item.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- 联系方式 -->


        </div>

    </div>
    </div>
</div>


<!-- 新闻中心 -->
<div class="container">
    <div class="row">

        <div class="col-xs-12 col-sm-9 col-md-9">
            <div class="newsBox">
                <div class="titleBar">
                    <h1>新闻中心</h1>
                    <span></span> <a class="rightMore" href="article.html">>></a>
                </div>
                <ul class="indexNewsList">

                    <li class="col-xs-12 col-sm-6 col-md-6">
                        <a href="article_detail.html">
                            <div class="img" style="background-image: url(/s/images/news/1.png)"></div>
                            <div class="txt">
                                <span class="title">
                                    网页前端将在网站中占据很大的空间和位置
                                </span>
                                <span class="time">[ 2017-01-01 ]</span>
                                <p>
                                    在全球范围内，目前对于大数据都有一个共识，即大数据技术的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”...
                                </p>
                            </div>
                        </a>
                    </li>

                    <li class="col-xs-12 col-sm-6 col-md-6">
                        <a href="article_detail.html">
                            <div class="img" style="background-image: url(/s/images/news/2.png)"></div>
                            <div class="txt">
                                <span class="title">
                                    微软欲主动送Windows Phone 7设备给黑客破解
                                </span>
                                <span class="time">[ 2017-01-01 ]</span>
                                <p>
                                    在全球范围内，目前对于大数据都有一个共识，即大数据技术的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”...
                                </p>
                            </div>
                        </a>
                    </li>

                    <li class="col-xs-12 col-sm-6 col-md-6">
                        <a href="article_detail.html">
                            <div class="img" style="background-image: url(/s/images/news/3.png)"></div>
                            <div class="txt">
                                <span class="title">
                                    友盟Android应用数据报告显示国内优质应用非常稀缺
                                </span>
                                <span class="time">[ 2017-01-01 ]</span>
                                <p>
                                    在全球范围内，目前对于大数据都有一个共识，即大数据技术的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”...
                                </p>
                            </div>
                        </a>
                    </li>

                    <li class="col-xs-12 col-sm-6 col-md-6">
                        <a href="article_detail.html">
                            <div class="img" style="background-image: url(/s/images/news/4.png)"></div>
                            <div class="txt">
                                <span class="title">
                                    万亿分期市场或崩盘？消费金融模式及风险深度报告
                                </span>
                                <span class="time">[ 2017-01-01 ]</span>
                                <p>
                                    在全球范围内，目前对于大数据都有一个共识，即大数据技术的战略意义不在于掌握庞大的数据信息，而在于对这些含有意义的数据进行专业化处理。换言之，如果把大数据比作一种产业，那么这种产业实现盈利的关键，在于提高对数据的“加工能力”，通过“加工”实现数据的“增值”...
                                </p>
                            </div>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
        <div class="col-xs-12 col-sm-3 col-md-3">
            <div class="contactBox" style="padding:10px;">
                <p>联系人：张经理</p>
                <p>手机：13800138000</p>
                <p>电话：020-88668888</p>
                <p>邮箱：mojocube@qq.com</p>
                <p>地址： 广东省广州市天河区天粤垦路88号</p>
            </div>
        </div>
    </div>
</div>

<div style="height: 10px;"></div>

</section>
{% endblock %}

templates/module/contact.html
<!-- 关注微信模态框（Modal）start -->
<div class="modal fade" id="wechatModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="border: 0px;">
            <div class="modal-header">请扫描二维码关注我们</div>
            <div class="modal-body" style="text-align: center">
                <img src="/s/images/qrcode.jpg" alt="" />
            </div>
            <div class="modal-footer" style="text-align: center;">
                <button type="button" class="btn btn-primary" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function showWechatQR() {
        $("#wechatModal").modal("show")
    }
</script>
<!-- 关注微信模态框（Modal）end -->

templates/product.html
{% extends 'base/base.html'%}
{% block base_content %}
<section>

<!-- 产品 -->
<div style="padding-top: 0px; margin-top:0px; padding-bottom:10px">

    <div class="container">
        <div class="row">
        <!-- 产品中心 -->
        <div class="col-xs-12 col-sm-8 col-md-9" id="rightBox">

            <div class="positionBox">
               <div class="titleBar">
                    <h1>当前位置</h1>
                    <span></span>
                    <a href="/">首页</a> > <a href="{% url 'product:product_index' %}">产品中心</a> > {{ category.name }}
                </div>
            </div>

            <div class="col-sm-12 col-md-12 pad">

                <div class="productList">
                    {% for item in products %}
                    <div class="col-xs-6 col-sm-4 col-md-3 col-mm-6 productImg">
                        <a title="{{ item.title }}" href='{% url "product:product_detail" product_id=item.id %}'>
                            <span class="imgLink-hover"><span class="hover-link"></span></span>
                            <img src="/s/upload/{{ item.image }}" alt="{{ item.title }}" />
                        </a>
                        <a class="productTitle" href="{% url "product:product_detail" product_id=item.id %}" title="{{ item.title }}">
                            {{ item.title }}
                        </a>
                    </div>
                    {% endfor %}

                </div>

            </div>

        </div>

        <!-- 产品分类 -->
        <div class="col-xs-12 col-sm-4 col-md-3">

            <div class="navigationBox" id="classification">
                <div class="titleBar">
                    <h1>产品分类</h1>
                    <span></span>
                </div>
                <div class="list">
                    <ul id="firstpane">
                        {% for item in categories %}
                        <li>
                            {% if item.name == category.name %}
                            <a class='' style="color: #3477c8;" href='{% url 'product:product' category_id=item.id %}'>
                            {% else %}
                            <a class='' href='{% url 'product:product' category_id=item.id %}'>
                            {% endif %}
                                {{ item.name }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!-- 联系方式 -->
        </div>

    </div>
    </div>
</div>

<div style="height: 10px;"></div>

</section>
{% endblock %}

templates/product_detail.html
{% extends 'base/base.html'%}
{% block base_content %}
<section>

<!-- 产品 -->
<div style="padding-top: 0px; margin-top:0px; padding-bottom:10px">

    <div class="container">
        <div class="row">
            <!-- 产品中心 -->
            <div class="col-xs-12 col-sm-8 col-md-9" id="rightBox">

                <div class="positionBox">
                   <div class="titleBar">
                        <h1>当前位置</h1>
                        <span></span>
                        <a href="/">首页</a> > <a href="{% url 'product:product_index' %}">产品中心</a> > <a href="{% url 'product:product' category_id=product.category.id %}">{{ product.category.name }}</a> > {{ product.title }}
                    </div>
                </div>

                <div class="col-sm-12 col-md-12 pad">

                        <div class="col-sm-12 col-md-6 pad">
                            <div class="detailGlide" style="max-width:600px; margin:0 auto">
                                <div class="slider">
                                    <ul class="slider__wrapper">
                                        <li data-responsive='' data-src='/s/upload/{{ product.image }}' data-sub-html='' class='slider__item real'><a><img src='/s/upload/{{ product.image }}'></a></li>
                                    </ul>
                                </div>
                                <div id="detailNav">
                                </div>
                            </div>
                            <script type="text/javascript">
                                var glide = $('.slider').glide({ navigationImg: true, navigation: "#detailNav" });
                            </script>
                        </div>

                        <div class="col-sm-12 col-md-6 pad">
                            <div class="detailTitle">
                                {{ product.title }}
                            </div>
                            <div class="detailParameter" style="line-height:1.8em;">
                                商品编号：20160704210343<br />
                                版本：V5<br />
                                架构：ASP.NET4.0+MSSQL/ACCESS<br />
                                点击次数：62<br />
                                上架时间：2016-07-04<br />
                            </div>

                        </div>

                        <div class="col-sm-12 col-md-12 pad" style="height: 20px;">

                        </div>

                        <div class="otherPageBox" style="background: none;margin: 0;padding: 0;">
                        </div>

                        <div class="aboutProduct">
                            <div class="titleBar">
                                <h1>相关产品</h1>
                                <span>&nbsp</span>
                            </div>
                            <div class="productList">
                                {% for item in related_products %}
                                <div class="col-xs-6 col-sm-4 col-md-3 col-mm-6 productImg">
                                    <a title="PRO-001" href='{% url "product:product_detail" product_id=item.id %}'>
                                        <span class="imgLink-hover"><span class="hover-link"></span></span>
                                        <img src="/s/upload/{{ item.image }}" alt="{{ item.title }}" />
                                    </a>
                                    <a class="productTitle" href="{% url "product:product_detail" product_id=item.id %}" title="{{ item.title }}">{{ item.title }}</a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>

                </div>

            <!-- 产品分类 -->
            <div class="col-xs-12 col-sm-4 col-md-3">

                <div class="navigationBox" id="classification">
                    <div class="titleBar">
                        <h1>产品分类</h1>
                        <span></span>
                    </div>
                    <div class="list">
                        <ul id="firstpane">
                            {% for item in categories %}
                            <li>
                                {% if item.name == category.name %}
                                <a class='' style="color: #3477c8;" href='{% url 'product:product' category_id=item.id %}'>
                                {% else %}
                                <a class='' href='{% url 'product:product' category_id=item.id %}'>
                                {% endif %}
                                    {{ item.name }}
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <!-- 联系方式 -->
            </div>
            </div>
        </div>
    </div>
</div>

<div style="height: 10px;"></div>

</section>
{% endblock %}